// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDds-NyxnFSG9UTuySEXP9O2CKrc-7g0YQ',
    appId: '1:947320406149:web:628db802cc62f264d2e9ec',
    messagingSenderId: '947320406149',
    projectId: 'memora-2b0b3',
    authDomain: 'memora-2b0b3.firebaseapp.com',
    storageBucket: 'memora-2b0b3.firebasestorage.app',
    measurementId: 'G-HRFJE5RE9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ADWO0ubPqVgNYIpm1xSuABHxP5VVDVw',
    appId: '1:947320406149:android:523b9ba32057add1d2e9ec',
    messagingSenderId: '947320406149',
    projectId: 'memora-2b0b3',
    storageBucket: 'memora-2b0b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4DKVA2Ex_uNqjBIqegvL7hCsGArWmSTo',
    appId: '1:947320406149:ios:9d9e1c246440a274d2e9ec',
    messagingSenderId: '947320406149',
    projectId: 'memora-2b0b3',
    storageBucket: 'memora-2b0b3.firebasestorage.app',
    iosBundleId: 'com.example.memora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4DKVA2Ex_uNqjBIqegvL7hCsGArWmSTo',
    appId: '1:947320406149:ios:9d9e1c246440a274d2e9ec',
    messagingSenderId: '947320406149',
    projectId: 'memora-2b0b3',
    storageBucket: 'memora-2b0b3.firebasestorage.app',
    iosBundleId: 'com.example.memora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDds-NyxnFSG9UTuySEXP9O2CKrc-7g0YQ',
    appId: '1:947320406149:web:90f4a09d1a509466d2e9ec',
    messagingSenderId: '947320406149',
    projectId: 'memora-2b0b3',
    authDomain: 'memora-2b0b3.firebaseapp.com',
    storageBucket: 'memora-2b0b3.firebasestorage.app',
    measurementId: 'G-N9EMWER1HS',
  );
}
